### PR TITLE
Add metadata for "Publish to BCR" app

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@stefanbucur This is the last step I can do. Afterwards, you need to follow step 1 and 3 from https://github.com/bazel-contrib/publish-to-bcr. Let me know if you have any questions.

**Comment by fmeum** [comment]
@stefanbucur Friendly ping

**Comment by stefanbucur** [comment]
> @stefanbucur Friendly ping

Whoops, thanks for the reminder! This slipped my attention. Trying to do this now.

**Comment by stefanbucur** [comment]
> > @stefanbucur Friendly ping
> 
> Whoops, thanks for the reminder! This slipped my attention. Trying to do this now.

Step 1 done, moving to step 3 (cutting a new release).

**Comment by stefanbucur** [comment]
> > > @stefanbucur Friendly ping
> > 
> > 
> > Whoops, thanks for the reminder! This slipped my attention. Trying to do this now.
> 
> Step 1 done, moving to step 3 (cutting a new release).

@fmeum I think both steps are done. Should I see anything updated somewhere?

**Comment by fmeum** [comment]
@stefanbucur This PR needs to be merged before creating the release, otherwise it won't trigger the app. After the merge, if you cut a release and something doesn't work, you should receive an email from the app.

**Comment by stefanbucur** [comment]
> @stefanbucur This PR needs to be merged before creating the release, otherwise it won't trigger the app. After the merge, if you cut a release and something doesn't work, you should receive an email from the app.

Argh! My apologies, I had somehow assumed I'm working on a Github issue, not PR. Let me merge this, then I'll cut v0.5.1.

**Comment by fmeum** [comment]
@stefanbucur Thanks for the new attempt, unfortunately it didn't work.

According to the author of the BCR app, @kormide:
> It looks like the app isn't installed to stefanbucur's BCR fork. It should have tried to send the error to the email here:
> <email in the metadata>

**Comment by stefanbucur** [comment]
> @stefanbucur Thanks for the new attempt, unfortunately it didn't work.
> 
> According to the author of the BCR app, @kormide:
> 
> > It looks like the app isn't installed to `stefanbucur`'s BCR fork. It should have tried to send the error to the email here:
> > `<email in the metadata>`

Per the BCR instructions at https://github.com/bazel-contrib/publish-to-bcr: "The fork can be in the same GitHub account as your ruleset or in the release author's personal account. If you use release automation and the release author is the github-actions bot, then the fork must be in ruleset's account unless you [override the releaser](https://github.com/bazel-contrib/publish-to-bcr/blob/main/templates/README.md#optional-configyml)."

The ruleset is under bazelbuild/ and the BCR repository is already there. Moreover, the configuration page didn't complain about anything, so I assumed this is the correct approach. I also didn't receive any notification email.

Why do I have to create a personal fork of the repository?

**Comment by kormide** [comment]
> > @stefanbucur Thanks for the new attempt, unfortunately it didn't work.
> > According to the author of the BCR app, @kormide:
> > > It looks like the app isn't installed to `stefanbucur`'s BCR fork. It should have tried to send the error to the email here:
> > > `<email in the metadata>`
> 
> Per the BCR instructions at https://github.com/bazel-contrib/publish-to-bcr: "The fork can be in the same GitHub account as your ruleset or in the release author's personal account. If you use release automation and the release author is the github-actions bot, then the fork must be in ruleset's account unless you [override the releaser](https://github.com/bazel-contrib/publish-to-bcr/blob/main/templates/README.md#optional-configyml)."
> 
> The ruleset is under bazelbuild/ and the BCR repository is already there. Moreover, the configuration page didn't complain about anything, so I assumed this is the correct approach. I also didn't receive any notification email.
> 
> Why do I have to create a personal fork of the repository?

The app does not have write permissions to the BCR (by design) and cannot push an entry there, so rulesets under bazelbuild are an exception.

Perhaps you didn't receive an email because a no-reply email is listed here? https://github.com/bazelbuild/rules_fuzzing/blob/master/.bcr/metadata.template.json#L5

**Pull request merged**
